In [1]:
# 라이브러리 불러오기

import pandas as pd
import numpy as np

In [3]:
dust = pd.read_excel('dust1.xlsx')
dust.head()

,지역,망,측정소코드,측정소명,측정일시,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [4]:
# 컬럼 이름 변경

dust = dust.rename(columns={'측정일시':'date'})
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소
0,서울 송파구,도시대기,111273,송파구,2021040101,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236
1,서울 송파구,도시대기,111273,송파구,2021040102,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236
2,서울 송파구,도시대기,111273,송파구,2021040103,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236
3,서울 송파구,도시대기,111273,송파구,2021040104,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236
4,서울 송파구,도시대기,111273,송파구,2021040105,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236

In [5]:
# 자료형 확인

dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date       int64
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [6]:
# 문자열로 형변환

dust['date'] = dust['date'].astype(str)
dust['date'] = dust['date'].str.slice(0,8)
dust.dtypes

지역           str
망            str
측정소코드      int64
측정소명         str
date         str
SO2      float64
CO       float64
O3       float64
NO2      float64
PM10       int64
PM25       int64
주소           str
dtype: object

In [ ]:
# 날짜형으로 형변환

dust['date'] = pd.to_datetime(dust['date'])
dust.dtypes

지역                  str
망                   str
측정소코드             int64
측정소명                str
date     datetime64[us]
SO2             float64
CO              float64
O3              float64
NO2             float64
PM10              int64
PM25              int64
주소                  str
dtype: object

# 날짜형을 년, 월, 일로 분리 추출

In [8]:
# dt 속성

dust['date'].dt

In [ ]:
dust['date'].dt.year # 연도 추출

0     2021
1     2021
2     2021
3     2021
4     2021
5     2021
6     2021
7     2021
8     2021
9     2021
10    2021
11    2021
12    2021
13    2021
14    2021
15    2021
16    2021
17    2021
18    2021
19    2021
20    2021
21    2021
22    2021
23    2021
24    2021
25    2021
26    2021
27    2021
28    2021
29    2021
30    2021
31    2021
Name: date, dtype: int32

## 년, 월, 일 컬럼 생성

In [10]:
dust['year'] = dust['date'].dt.year
dust['month'] = dust['date'].dt.month
dust['day'] = dust['date'].dt.day

In [11]:
dust.head()

,지역,망,측정소코드,측정소명,date,SO2,CO,O3,NO2,PM10,PM25,주소,year,month,day
0,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,1.0,0.002,0.066,50,18,서울 송파구 백제고분로 236,2021,4,1
1,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.058,48,20,서울 송파구 백제고분로 236,2021,4,1
2,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.055,44,20,서울 송파구 백제고분로 236,2021,4,1
3,서울 송파구,도시대기,111273,송파구,2021-04-01,0.003,0.8,0.002,0.055,40,20,서울 송파구 백제고분로 236,2021,4,1
4,서울 송파구,도시대기,111273,송파구,2021-04-01,0.004,0.8,0.002,0.053,38,17,서울 송파구 백제고분로 236,2021,4,1

# 데이터 병합

In [12]:
s1 = pd.read_excel('nation.xlsx')
s2 = pd.read_excel('code.xlsx')

In [14]:
s1.head()

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486

In [15]:
s2.head()

  국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주

## merge()

- pd.merge(데이터프레임1, 데이터프레임2, on=기준컬럼명, how='조인형식')
- how : inner(기본값), outer, left, right

In [16]:
# 국적 코드 컬럼 기준

pd.merge(s1, s2, on='국적코드')

  국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

In [17]:
# 오른쪽 컬럼 기준(차집합)

pd.merge(s1, s2, on='국적코드', how='right')

   국적코드   성별      입국객수      증가수  국적명
0   A01   남성  125000.0   8000.0  필리핀
1   A01   여성  130000.0  10000.0  필리핀
2   A02  NaN       NaN      NaN   일본
3   A03  NaN       NaN      NaN   미국
4   A04  NaN       NaN      NaN   중국
5   A05   남성     300.0     10.0   호주
6   A05   여성     200.0     50.0   호주
7   A06   남성  158912.0  24486.0  베트남
8   A06   여성  325000.0  63466.0  베트남
9   A07  NaN       NaN      NaN  스위스
10  A99  NaN       NaN      NaN   기타

# 데이터 그룹핑

## groupby()

In [ ]:
# 국적코드별 성별, 입국객수, 증가수

s1.groupby('국적코드').sum()

        성별    입국객수    증가수
국적코드
A01   남성여성  255000  18000
A05   남성여성     500     60
A06   남성여성  483912  87952

In [ ]:
# 국적코드, 성별 -> 입국객수, 증가수

s1.groupby(['국적코드', '성별']).sum()

           입국객수    증가수
국적코드 성별
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

연습문제 1

In [ ]:
# 1-1
# 파일 불러오기

co = pd.read_csv('covid.csv', index_col=0)
co

        사례수    증가    감소  변화없음
항목
스마트폰    999  78.9   1.7  19.4
텔레비전    965  68.5   3.9  27.6
개인용 PC  973  65.7   3.7  30.6
태블릿 PC  662  46.8   4.2  49.0
라디오     687  35.5  12.5  52.0
잡지·책    776  31.3  17.8  50.9
종이신문    552  17.6  23.2  59.2

In [73]:
# 1-2
# 사례수 가장 높은 항목

co[co['사례수'] == co['사례수'].max()]

      사례수    증가   감소  변화없음
항목
스마트폰  999  78.9  1.7  19.4

In [ ]:
# 1-3
# 증가율 높은 항목 3개

co1 = co.sort_values(by='증가', ascending=False)
co1.head(3)

        사례수    증가   감소  변화없음
항목
스마트폰    999  78.9  1.7  19.4
텔레비전    965  68.5  3.9  27.6
개인용 PC  973  65.7  3.7  30.6

연습문제 2

In [74]:
# 2-1
# 파일 불러와서 하위 5행 확인

va = pd.read_csv('vaccine.csv')
va.tail()

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [75]:
# 2-2
# 열 삭제

va = va.drop(['day1sum', 'day1rate', 'day2sum', 'day2rate'], axis=1)
va

           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [76]:
# 2-3
# 기초통계량

va.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [77]:
# 2-4
# 월별 평균 출력

va['date']

0      2021.10.16
1      2021.10.15
2      2021.10.14
3      2021.10.13
4      2021.10.12
          ...
174    2021.04.25
175    2021.04.24
176    2021.04.23
177    2021.04.22
178    2021.04.21
Name: date, Length: 179, dtype: str

In [78]:
va['date'] = pd.to_datetime(va['date'])

va['month'] = va['date'].dt.month
va

          date  subject  day1num  day2num  month
0   2021-10-16  9505868    10673    66910     10
1   2021-10-15  9505868    14556   133580     10
2   2021-10-14  9505868     9609    94569     10
3   2021-10-13  9505868     9804    77503     10
4   2021-10-12  9505868    17274   110204     10
..         ...      ...      ...      ...    ...
174 2021-04-25  1023346    23323     3411      4
175 2021-04-24  1023346      200        0      4
176 2021-04-23  1027740    10195      119      4
177 2021-04-22  1023538    27074     2479      4
178 2021-04-21  1019322    22501     2358      4

[179 rows x 5 columns]

In [79]:
va1 = va.groupby('month').mean()

va1.loc[:, ['day1num', 'day2num']]

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000

연습문제 3

In [ ]:
# 3-1
# merge

s = pd.read_csv('signup.csv')
p = pd.read_csv('professor.csv')

pd.merge(s, p, on='담당교수')

   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [85]:
# 3-2
# 학과별 인원수

p.groupby('학과').count()

       담당교수
학과
인공지능      2
정보통신      1
컴퓨터공학     2