In [ ]:
# shift + enter : 코드 실행 후 다음 셀 자동 생성
print('Hello world')

Hello world

# 판다스 객체 생성

- 시리즈(Series) : 1차원 배열 ex)[1, 2, 3]
- 데이터프레임(DataFrame) : 행과 열을 가지는 2차원 배열(표) ex)엑셀

## 시리즈(Series) 만들기

### 판다스 라이브러리 불러오기

In [4]:
import pandas as pd

In [5]:
score = pd.Series([95, 90, 85, 90, 95])
score

0    95
1    90
2    85
3    90
4    95
dtype: int64

In [8]:
# 실수형 시리즈 만들기
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
s

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

### 인덱스 직접 지정

In [9]:
s = pd.Series([90, 80, 95], index=['A', 'B', 'C'])

In [13]:
s

A    90
B    80
C    95
dtype: int64

## 데이터프레임(DataFrame) 만들기

### 넘파이(numpy)로 배열 생성

In [1]:
import numpy as np

arr = np.arange(12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [2]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

In [5]:
# 넘파이 배열 -> 데이터프레임
df = pd.DataFrame(arr)
df

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [6]:
print(df)

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

### 딕셔너리로 데이터프레임 생성하기

In [11]:
df = pd.DataFrame({
    'name':['나루토', '사스케', '사쿠라'],
    'score':[50, 90, 95],
    'dept':['com', 'eng', 'math']
})

In [12]:
df

  name  score  dept
0  나루토     50   com
1  사스케     90   eng
2  사쿠라     95  math

### csv 파일 불러오기

In [13]:
df = pd.read_csv('mobile.csv')
df

     Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [ ]:
df = pd.read_csv('mobile.csv', index_col=0) # 0번 행을 index로 지정
df

          Color  price
Brand
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

# 판다스 데이터 확인

In [15]:
filename = 'weather.csv'
df = pd.read_csv(filename)
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df.shape # (행, 열)

(3653, 4)

EDA (탐색적 데이터 분석)

## head() : 데이터의 앞부터 확인

In [17]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [18]:
df.head(10)

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6
5  2010-08-06  26.8       9.8        8.0
6  2010-08-07  27.5       9.1        5.0
7  2010-08-08  26.6       5.9        4.0
8  2010-08-09  26.9       5.1        3.1
9  2010-08-10  25.6      10.2        5.5

## tail() : 데이터의 뒤부터 확인

In [19]:
df.tail()

            date  temp  max_wind  mean_wind
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [20]:
df.tail(2)

            date  temp  max_wind  mean_wind
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

## info() : 데이터의 전반적인 정보

In [ ]:
df.info() # non-null count -> max_wind, mean_wind는 결측치가 있다

<class 'pandas.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       3653 non-null   str
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), str(1)
memory usage: 114.3 KB

## index : 인덱스 출력

In [22]:
df.index

RangeIndex(start=0, stop=3653, step=1)

## columns : 컬럼(열) 출력

In [23]:
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='str')

## describe() : 요약 통계량

In [ ]:
df.describe() # 자료형 - 숫자(정수, 실수)

              temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

### 기온(temp) 컬럼의 내용

- 데이터프레임명[컬럼명].메서드명()

In [27]:
df['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [ ]:
print(df['temp'].mean()) # 평균

12.942102381604162

In [ ]:
df['temp'].sum() # 합계

np.float64(47277.5)

In [ ]:
df['temp'].median() # 중간값

np.float64(13.8)

In [31]:
df['temp'].std() # 표준편차

np.float64(8.538507014753446)

In [32]:
df['temp'].var() # 분산

np.float64(72.90610204099379)

In [ ]:
df['temp'].max() # 최대값

np.float64(31.3)

In [ ]:
df['temp'].min() # 최소값

np.float64(-9.0)

## sort_values() : 데이터 크기순 정렬

- ascending = True (생략) -> 오름차순
- ascending = False -> 내림차순
- by = [컬럼명] : 기준

In [35]:
# 최대 풍속(max_wind) 데이터 크기에 따라 오름차순 정렬

df.sort_values(by='max_wind')

            date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1005  2013-05-02   7.1       2.2        0.8
1512  2014-09-21  20.4       2.2        1.2
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [36]:
# 최대 풍속(max_wind) 데이터 크기에 따라 내림차순 정렬

df.sort_values(by='max_wind', ascending=False)

            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

## value_counts() : 빈도 분석 결과

In [37]:
filename = 'bank.csv'
bank = pd.read_csv(filename)
bank.head()

           job  education  balance  duration   y
0   management   tertiary     2143       261  no
1   technician  secondary      265       348  no
2  blue-collar  secondary       -7       365  no
3   technician  secondary       -3      1666  no
4   technician  secondary     -103       145  no

In [ ]:
bank['job'].value_counts() # 기본값 : ascending=False

job
management       1560
blue-collar      1499
technician       1206
admin.            834
services          661
retired           351
self-employed     256
entrepreneur      239
unemployed        223
housemaid         208
student           153
Name: count, dtype: int64

In [41]:
bank['job'].value_counts(ascending=True)

job
student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: count, dtype: int64

## unique() : 해당 열의 고유값

In [42]:
bank['job'].unique()

<StringArray>
[   'management',    'technician',   'blue-collar',       'retired',
      'services',        'admin.',  'entrepreneur', 'self-employed',
    'unemployed',       'student',             nan,     'housemaid']
Length: 12, dtype: str