# 판다스 데이터 선택

## 컬럼(열) 선택

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('weather.csv')
df

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [4]:
df['temp']

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [5]:
df.temp

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [6]:
type(df['temp'])

pandas.Series

### 여러 컬럼 선택

In [7]:
df[['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [8]:
type(df[['date', 'temp']])

pandas.DataFrame

## loc

- 데이터프레임명.loc[행, 열]

In [9]:
df.head()

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [ ]:
df.loc[0,'temp'] # 행 생략 불가

np.float64(28.7)

In [15]:
df.loc[0] # 열 생략 가능

date         2010-08-01
temp               28.7
max_wind            8.3
mean_wind           3.4
Name: 0, dtype: object

In [16]:
df.loc[:, 'temp'] # : 전체 선택

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ...
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64

In [28]:
df.loc[:, ['date', 'temp']]

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [34]:
df.loc[:, 'date':'max_wind']

            date  temp  max_wind
0     2010-08-01  28.7       8.3
1     2010-08-02  25.2       8.7
2     2010-08-03  22.1       6.3
3     2010-08-04  25.3       6.6
4     2010-08-05  27.2       9.1
...          ...   ...       ...
3648  2020-07-27  22.1       4.2
3649  2020-07-28  21.9       4.5
3650  2020-07-29  21.6       3.2
3651  2020-07-30  22.9       9.7
3652  2020-07-31  25.7       4.8

[3653 rows x 3 columns]

## iloc

- i : integer
- 데이터프레임명.iloc[행, 열]

In [29]:
df.head(3)

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [36]:
df.iloc[0, [0, 1]]

date    2010-08-01
temp          28.7
Name: 0, dtype: object

In [31]:
df.iloc[1:3] # 1번, 2번 행

         date  temp  max_wind  mean_wind
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9

In [32]:
df.iloc[:, 0:2] # 0번, 1번 열

            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [33]:
df.iloc[1:4, 0:3] # 1~3번 행, 0~2번 행

         date  temp  max_wind
1  2010-08-02  25.2       8.7
2  2010-08-03  22.1       6.3
3  2010-08-04  25.3       6.6

## bool 인덱싱

In [ ]:
w = df['temp'] >= 30
df[w] # True만 추출

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6
1104  2013-08-09  30.6       9.9        6.4
1105  2013-08-10  30.6       7.4        3.8
2913  2018-07-23  30.5       6.5        1.6
2925  2018-08-04  30.3       5.8        3.0

In [40]:
df[df['temp'] >= 30]

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6
1104  2013-08-09  30.6       9.9        6.4
1105  2013-08-10  30.6       7.4        3.8
2913  2018-07-23  30.5       6.5        1.6
2925  2018-08-04  30.3       5.8        3.0

### 조건에 맞는 데이터 추출

In [41]:
# 온도가 가장 높은 날의 모든 정보(행)

w = df['temp'] == df['temp'].max()
df[w]

            date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6

### 조건 2개 이상

- and - &
- or - |

In [43]:
# 기온이 30도 이상이고, 최대 풍속이 9 이상인 데이터

w = (df['temp'] >= 30) | (df['max_wind'] >= 9)
df[w]

            date  temp  max_wind  mean_wind
4     2010-08-05  27.2       9.1        5.6
5     2010-08-06  26.8       9.8        8.0
6     2010-08-07  27.5       9.1        5.0
9     2010-08-10  25.6      10.2        5.5
10    2010-08-11  24.6       9.4        4.8
...          ...   ...       ...        ...
3632  2020-07-11  20.1      10.3        4.1
3634  2020-07-13  17.8      10.3        4.6
3635  2020-07-14  17.8      12.7        9.4
3641  2020-07-20  23.0      11.2        7.3
3651  2020-07-30  22.9       9.7        2.4

[1218 rows x 4 columns]

# 판다스 결측데이터 처리

## isna() : 값이 nan(결측치) -> True

In [45]:
# 최대 풍속이 측정되지 않은 모든 데이터 출력

df[df['max_wind'].isna()]

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

## 데이터프레임명.isnull().sum() : 컬럼별 결측데이터 개수

- isnull의 값
    - 0 : False
    - 1 : True

In [ ]:
df.isnull().sum() # 컬럼별

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [ ]:
df.isnull().sum().sum() # 전체 데이터프레임

np.int64(10)

## dropna() : 결측데이터 삭제

In [49]:
df.dropna() # 결측치 제거한 상태 확인

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [50]:
df # 원본의 결측치가 제거되지 않음

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [52]:
df2 = df.dropna() # 결측치 제거한 상태를 새로운 데이터프레임에 저장
df2

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3646 rows x 4 columns]

In [53]:
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [54]:
df.isnull().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

## fillna(대체값) : 결측데이터 대체

In [55]:
df['max_wind'].isnull().sum()

np.int64(4)

In [56]:
df3 = df.copy() # 복사
df3

            date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df3 = df3.fillna(0) # 결측치 모두 0으로 채움

In [58]:
df3.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
# 평균

avg = df3['max_wind'].mean()
avg

np.float64(7.902436353681905)

In [60]:
df3['max_wind'] = df3['max_wind'].fillna(avg)

In [61]:
avg2 = df3['mean_wind'].mean()
avg2

np.float64(3.9299753627155765)

In [62]:
df3['mean_wind'] = df3['mean_wind'].fillna(avg2)

In [63]:
df3.tail(10)

            date  temp  max_wind  mean_wind
3643  2020-07-22  22.2       4.3        1.9
3644  2020-07-23  21.5       4.9        2.3
3645  2020-07-24  20.4       7.2        2.8
3646  2020-07-25  20.7       3.8        1.1
3647  2020-07-26  21.4       4.8        2.8
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5